# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c8c084157f62f3b72d7f17510f85e751db19cafcaf9ef27cbe77d76295b2d983b18897f0945ed1eb061f181c8d8dc4b937b3b0846af3f486eddb18bda55fdce

test:
  secret_key_base: 186faeae2b3dfe22713932c312f348829db343ab7f8fb936907009ec41eaf273de9a99e230f192e214c6ecb752198703abe5918cfcea87f110cd8f0b3642bec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
